### ISSUE TITLE
Tron skin not working

### ISSUE THREAD

**Issue by chinookproject** [aterrien/jQuery-Knob#119]
I'm trying out the plugin, but it seems like the Tron skin isn't working for me. It simply shows the 'default' look.

Is this a known issue? And anyone any idea how i could fix  this problem?

**Comment by whimsicaldreamer** [comment]
@chinookproject, @aterrien  Me too can't get it to work. Can you show us a solution of how you did that? I am using this but can't get it to work. Neither can I get the units to work.

```
    <script>
        $(function() {
            $('.dial').knob({
                thickness: 0.2,
                lineCap: "round",
                readOnly: true,
                fgColor: "#D07321",
                inputColor: "#3e4040",
                skin: "tron"
            });
        });
    </script>
```
