### ISSUE TITLE
Using $(this) inside events.

### ISSUE THREAD

**Issue by happyiphone** [aterrien/jQuery-Knob#237]
I've been trying to get other pieces of information from withing an event but it is impossible. If I use the id of the element it works great. It would be really useful if we have access to $(this) inside events (think in terms of generic event handlers, several controls one piece of code for the handler).

Thanks!

**Comment by breem** [comment]
Hi,

How did you get the id of the triggering knob inside your event? I have multiple knobs on one page and I need the id of the triggering knob to post to the backend code.

Thanks in advance,

Mark

**Comment by happyiphone** [comment]
As I mentioned on my previous post, just use $($(this)[0].$[0]) as $(this) and from there you can access anything you want for the object posting the event. It could be $($(this)[0].$[0]).data('id') if that's what you are looking for.

**Comment by breem** [comment]
Hi,

Thanks for your response! I got it to work. As I am using web.py I could not use the $ notation for jQuery instead of that I use "jQuery" where you use "$". Eventually I got the id of the control using:

jQuery(this)[0].$.context.id
