### ISSUE TITLE
Setting the value does not update the dial

### ISSUE THREAD

**Issue by reallyroy** [aterrien/jQuery-Knob#252]
Hi Anthony

When I set the value for my dial like so:
```javascript
<script>
    $('.dial')
        .val(27)
        .trigger('change');
</script>
```

The input value gets updated correctly, but the dial doesn't get updated. Am I missing something?

Also, the change event doesn't get hit. But that's already been raised as another issue.

I have created a pen for the same.
http://codepen.io/anon/pen/yyeqVP

Regards,
Roy

**Comment by dillonlucente** [comment]
Not a solution to the problem, but triggering 'blur' on the input after manually changing the value worked for me.

**Comment by reallyroy** [comment]
Hi dillonlucente,

Thanks. That worked. 

@aterrien 

I won't close the issue since, from what I understand, this is a workaround not a fix. Do correct me if that is not the case.

Thanks & Regards,
Roy

**Comment by reallyroy** [comment]
Interestingly, the original code (below)  also works now. Not sure what is different now as opposed to then.
````javascript
$('.dial')
        .val(27)
        .trigger('change');
````

Closing this issue. Will open a new one if I face the issue again or have a better understand of why.

Thanks,
Roy

**Comment by cSmout** [comment]
Hi @reallyroy and @dillonlucente, 
I am also experiencing this bug of the dial not updating after triggering 'change'. The value updates, but the dial does not.
Could you please clarify what you meant by triggering 'blur' on input? I'm probably missing something, but there is no method named 'blur' that I can see.
Thanks!

**Comment by dillonlucente** [comment]
Sure, so what I do when setting an updated value is:

```javascript
$("#loading-ring").val(45).trigger("blur");
```

It's just triggering the js blur event on the knob's input tag. 

[This](https://github.com/aterrien/jQuery-Knob/blob/master/js/jquery.knob.js#L173) line shows the element is set to redraw on change and blur, so it just needed to be forced into that. Either ```change``` or ```blur``` should work, but I found it consistently worked with blur. As he mentioned, ```change``` magically started working again, even though the repo wasn't updated, so I'm inclined to think it was something in the browser that was either broken or fixed.

I hope that helps.

**Comment by cSmout** [comment]
Thanks for your reply, triggering blur works for me too. I thought it might have been something browser related, but I had the same bug in Safari on an iPad as well as chrome on my machine... no such magical revival of functionality for me! But this works for now, thanks again

**Comment by cSmout** [comment]
Sorry to bother you guys again, I realise this isn't a support forum! Feel free to redirect me somewhere else...
I've come back to my work machine, and even though the blur and change methods worked (updated the dial) in codepen at home, they do not work in my actual script.

I'm receiving a value in a xmlhttp response that I want to set a knob with. 
When i have the value, I am calling:
' ' 'javascript
    $("#wave_knob)
    .trigger('configure', {"max":waveMax})
     .val(midi_val)
     .trigger('change');
' ' '

and my knob() fucntion is simply as follows for now (doesn't get called):
' ' ' javascript
$(".knob").knob({
    'change' : function (value) {
      console.log("Knob Change in xhr_poll");
    }
});
' ' '

I would appreciate any thoughts!

**Comment by dillonlucente** [comment]
Unfortunately, I don't think that change hook is wired to making manual changes. From a quick scan of the code, it looks like it's called on touch or mouse events. You're using jQuery, so you can probably just add a listener to the change event directly on your input. This should work:

```javascript
$(".knob").knob();

$("#wave_knob").on("change", function(event) {
     console.log("Knob Change in xhr_poll " + $(this).val());
});

// Then set the value as above in your ajax request
```

Hope that helps.

**Comment by cSmout** [comment]
Thanks again for your reply! It is unfortunate... Strange though, how in the above codepen sketch, the dial does indeed get updated from a 'manual' change (from the button).
It seems that using a listener on the change event does not work either, as the change event doesn't event get triggered, and therefore the callback does not either.

**Comment by cSmout** [comment]
@aterrien
Is there a way to just trigger a redraw on the dial when a new val is set using val()? Aside from triggering 'change' which doesn't seem to work for me...
