### ISSUE TITLE
NPM

### ISSUE THREAD

**Issue by theofidry** [aterrien/jQuery-Knob#257]
Add NPM package.

**Comment by kopax** [comment]
+1, i wanted to use it with browserify, the paquet is now compatible commonjs

    npm install aterrien/jQuery-Knob --save-dev
    npm install git+https://git@github.com:aterrien/jQuery-Knob.git --save-dev
    npm install git+ssh://git@github.com:aterrien/jQuery-Knob.git --save-dev

did not work

**Comment by whmountains** [comment]
No, It doesn't work.
