### ISSUE TITLE
Dynamically Changing 'displayInput' Option

### ISSUE THREAD

**Issue by jakeholland** [aterrien/jQuery-Knob#267]
I am having trouble with displayInput updating correctly. The code I have written has two knobs within each other. and as you change the outer knob the value should show. It does not however. [The code can be found here](https://jsfiddle.net/jtholla2/wp8ve8rb/2/). In an unrelated note, of which I really haven't explored, the font is of different sizes for the 2 knobs.

**Comment by sunsetrainbow** [comment]
The way you wrote it you're trying to modify the HTML input element only. Look at the knob documentation in the 'Hook' section.  Functions like change/release get certain things passed to them. And you probably want to use 'this.o' -- see docs.
