### ISSUE TITLE
How to change number font size + scrolling gives weird decimal points?

### ISSUE THREAD

**Issue by harryn** [aterrien/jQuery-Knob#269]
Is there a way to change number font size smaller so that the knob itself remains the same size?

I'm getting a weird issue when using step 0.1. When scrolling it sometimes gets a value like 5.100000000000000000098. What might be causing this?

You can see the test here http://skrail.planet.ee/proovs/jQuery-Knob-master/proov.php

**Comment by harryn** [comment]
Okay, found this for that weird issue: https://github.com/aterrien/jQuery-Knob/pull/78

But still, is it possible to change font size?

**Comment by jerrytan86** [comment]
you can edit font size using css, just add !important to override the default size:

#knob {
    font-size: 18px !important;
}

in jquery:

$("#knob").css("font-size","18px");

**Comment by Khrysller** [comment]
As knob is a class, it should be:
```css
.knob {
font-size: 18px !important;
}
```
