### ISSUE TITLE
Knob does not work in my IE 8

### ISSUE THREAD

**Issue by rsolov** [aterrien/jQuery-Knob#271]
Hi.

I have just tested jQuery-Knob in my IE 8 on demo page http://anthonyterrien.com/knob/. 

![ie](https://cloud.githubusercontent.com/assets/7485626/6546023/d90dd0ec-c5aa-11e4-8caf-ca30d85d6633.png)

Thanks

**Comment by rsolov** [comment]
How can I make revert counting? For example, from 30 to 0.

**Comment by PedroBorracho** [comment]
I faced the same, and the issue seems to be only the fact that the plugin is initializing canvas before excanvas gets ready: "ready" event is fired to early in IE8

To make it work, I used $(window).load instead of $(document).ready
