### ISSUE TITLE
Bower issue

### ISSUE THREAD

**Issue by xcopy** [aterrien/jQuery-Knob#283]
Look what I got when I run `bower install aterrien/jQuery-Knob`

```
bower jQuery-Knob#*             cached git://github.com/aterrien/jQuery-Knob.git#1.2.11
bower jQuery-Knob#*           validate 1.2.11 against git://github.com/aterrien/jQuery-Knob.git#*
bower                        ENOTFOUND Package aterrien/jQuery-Knob=aterrien/jQuery-Knob not found
```

**Comment by mschinis** [comment]
running `bower install jquery-knob` worked.

**Comment by felipembbraga** [comment]
works, but when I try to update, it gives the same error above.

**Comment by felipembbraga** [comment]
ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/aterrien/jQuery-Knob=jquery-knob.git", exit code of #128 fatal: unable to access 'https://github.com/aterrien/jQuery-Knob=jquery-knob.git/': The requested URL returned error: 400

    Additional error details:
    fatal: unable to access 'https://github.com/aterrien/jQuery-Knob=jquery-knob.git/': The requested URL returned error: 400

**Comment by dinko** [comment]
I have a similar error when running ```bower update``` while ```bower install``` worked fine.

```
ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/aterrien/jQuery-Knob=jquery-knob.git", exit code of #128 fatal: remote error:    aterrien/jQuery-Knob=jquery-knob is not a valid repository name   Email support@github.com for help

Additional error details:
fatal: remote error:
  aterrien/jQuery-Knob=jquery-knob is not a valid repository name
```

Maybe some sort of case-sensitivity issue?

**Comment by gilsondev** [comment]
It's not work. This issue was fixed?

**Comment by alvarotrigo** [comment]
I believe it might be related with the package name. `aterrien/jQuery-Knob` doesn't sound very normal anyway.

**Comment by xcopy** [comment]
Guys, look at [bower.json](https://github.com/aterrien/jQuery-Knob/blob/master/bower.json#L2)

Is it good practice? See http://bower.io/docs/creating-packages/#name

**Comment by stones** [comment]
I was having the same issue. I ended up using another bower package to the same repo:
```
bower install --save jknob
```
And that worked for me.

**Comment by tlartaud** [comment]
same here.
```
bower jQuery-Knob=jquery-knob#~1.2.11          ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/aterrien/jQuery-Knob=jquery-knob.git", exit code of #128 fatal: remote error:    aterrien/jQuery-Knob=jquery-knob is not a valid repo
sitory name   Email support@github.com for help
```

Please wake up.

**Comment by tlartaud** [comment]
Using bower command to install Knob does not work for me, i have to manually add the following line into bower.json, and then run `bower update`

```
"jknob": "~1.2.11"
```

So boring, fix ... fix ....

**Comment by aterrien** [comment]
1.2.12 should fix version mismatch. 

Using jquery-knob package should work :
$ bower install jquery-knob

**Comment by tlartaud** [comment]
@aterrien Thanks.

**Comment by xcopy** [comment]
Okay, what you gonna say now?

Install:
```
$ bower install jquery-knob
bower jquery-knob#*             cached git://github.com/aterrien/jQuery-Knob.git#1.2.12
bower jquery-knob#*           validate 1.2.12 against git://github.com/aterrien/jQuery-Knob.git#*
bower aterrien/jQuery-Knob#~1.2.12          install aterrien/jQuery-Knob#1.2.12

aterrien/jQuery-Knob#1.2.12 bower_components/aterrien/jQuery-Knob
└── jquery#2.1.4
```

Uninstall:
```
$ bower uninstall jquery-knob
bower not-installed 'jquery-knob' cannot be uninstalled as it is not currently installed
```

**Comment by tlartaud** [comment]
@xcopy Maybe try `bower cache clean` before installation ?

**Comment by xcopy** [comment]
@tlartaud, same 

```
$ bower cache clean
...

$ bower install jquery-knob
bower jquery-knob#*         not-cached git://github.com/aterrien/jQuery-Knob.git#*
bower jquery-knob#*            resolve git://github.com/aterrien/jQuery-Knob.git#*
bower jquery-knob#*           download https://github.com/aterrien/jQuery-Knob/archive/1.2.12.tar.gz
bower jquery-knob#*            extract archive.tar.gz
bower jquery-knob#*           resolved git://github.com/aterrien/jQuery-Knob.git#1.2.12
bower aterrien/jQuery-Knob#~1.2.12          install aterrien/jQuery-Knob#1.2.12

aterrien/jQuery-Knob#1.2.12 bower_components/aterrien/jQuery-Knob
└── jquery#2.1.4
```

**Comment by tlartaud** [comment]
@xcopy didn't try on my side yet :/ Can't help you on this sry. I'm using 'jknob' actually, and i really don't understand why there are so much slugs to install a single package ...

**Comment by tlartaud** [comment]
@xcopy What is the line added in your bower.json file after running this command ?

**Comment by xcopy** [comment]
Actually, I needed some Angular lib. I found it. Look what I've got.

```
bower install angular-knob
bower angular-knob#*        not-cached git://github.com/yunlzheng/angular-knob.git#*
bower angular-knob#*           resolve git://github.com/yunlzheng/angular-knob.git#*
bower angular-knob#*          download https://github.com/yunlzheng/angular-knob/archive/0.0.2.tar.gz
bower angular-knob#*           extract archive.tar.gz
bower angular-knob#*          resolved git://github.com/yunlzheng/angular-knob.git#0.0.2
bower jquery-knob#~1.2.3        cached git://github.com/aterrien/jQuery-Knob.git#1.2.12
bower jquery-knob#~1.2.3      validate 1.2.12 against git://github.com/aterrien/jQuery-Knob.git#~1.2.3
bower jquery#~2.0.3         not-cached git://github.com/jquery/jquery.git#~2.0.3
bower jquery#~2.0.3            resolve git://github.com/jquery/jquery.git#~2.0.3
bower jquery#~2.0.3           download https://github.com/jquery/jquery/archive/2.0.3.tar.gz
bower jquery#~2.0.3            extract archive.tar.gz
bower jquery#~2.0.3       invalid-meta jquery is missing "ignore" entry in bower.json
bower jquery#~2.0.3           resolved git://github.com/jquery/jquery.git#2.0.3

angular-knob#0.0.2 bower_components/angular-knob
├── angular#1.4.7
├── jquery#2.1.4
└── jquery-knob#1.2.12

jquery-knob#1.2.12 bower_components/jquery-knob
└── jquery#2.1.4
```

In this case works as expected.

Odd.

**Comment by xcopy** [comment]
@tlartaud, now with `--save` option

```
$ bower install jquery-knob --save
bower jquery-knob#*             cached git://github.com/aterrien/jQuery-Knob.git#1.2.12
bower jquery-knob#*           validate 1.2.12 against git://github.com/aterrien/jQuery-Knob.git#*
bower aterrien/jQuery-Knob#~1.2.12          install aterrien/jQuery-Knob#1.2.12

aterrien/jQuery-Knob#1.2.12 bower_components/aterrien/jQuery-Knob
└── jquery#2.1.4
```

bower.json
```json
{
   ...
  "dependencies": {
   ...
    "aterrien/jQuery-Knob": "jquery-knob#~1.2.12"
  }
}
```

**Comment by tlartaud** [comment]
@xcopy try replacing the line `"aterrien/jQuery-Knob": "jquery-knob#~1.2.12"` by something like `"aterrien/jQuery-Knob": "~1.2.12"` or `"jquery-knob": "~1.2.12"` or `"jknob": "~1.2.12"` and then run `bower update`

**Comment by xcopy** [comment]
@tlartaud, yea `"jquery-knob": "~1.2.12"` and `"jknob": "~1.2.12"` works as expected.

I don't understand, why `bower install jquery-knob` goes wrong.

Pay attention to the name of the package in [bower.json](https://github.com/aterrien/jQuery-Knob/blob/master/bower.json): it's `"name": "aterrien/jQuery-Knob"`.

Confused.

**Comment by tlartaud** [comment]
@xcopy same confusion here.

**Comment by tlartaud** [comment]
@aterrien i'm not sure that bower really allow you to use `/` characters in names ... This works with composer, but I've never seen a bower.json including a namespace. Maybe that using a name like `"name": "jquery-knob"` would fix the problem ?

**Comment by xcopy** [comment]
@tlartaud, I have already [mentioned this](https://github.com/aterrien/jQuery-Knob/issues/283#issuecomment-143692743) more than month ago :)

**Comment by lucaswxp** [comment]
+1

**Comment by robsilva** [comment]
I fixed it by manually deleting the folder under bower_components and manually editing bower.json to "jquery-knob": "~1.2.12" and finally, running "bower update"

**Comment by andersonkruger** [comment]
@aterrien as defined on bowers [name definition](http://bower.io/docs/creating-packages/#name):

 "Bower doesn’t support GitHub-style namespacing (org/repo), however you are encouraged to namespace related packages with -, for example, angular- and paper-."

"aterrien/jQuery-Knob" is an invalid name.. you should remove the '/' character...

**Comment by tlartaud** [comment]
@andersonkruger yup, we all mentioned this to him for 6 months ago. Awesome reactivity ^^

**Comment by aterrien** [comment]
Released 1.2.13 with valid package name ... waiting to see how bower.io/search react to this :/

**Comment by xcopy** [comment]
Now, looks good. Install/uninstall works as expected.

http://bower.io/search/?q=jquery-knob

![bower search](https://cloud.githubusercontent.com/assets/202339/11866948/5746a45e-a4d8-11e5-93ae-3053289a0d96.png)

**Comment by kakarlus** [comment]
very timely update :+1:
