### ISSUE TITLE
Change color of meter dynamically

### ISSUE THREAD

**Issue by shushiej** [aterrien/jQuery-Knob#310]
Hi, im using Knob.js for a Dashing project to show a color indicated progress meter for a particular project. But I am not able to find a way to dynamically change the color of the meter. From the image below you can see that only the color of the value changes, but the actual color of the meter remains the same color it was when it first loaded. This maybe due to the fact that the inline-styling is overriding my implementation, but im trying to find workarounds to fix this. Any Ideas?
![meter](https://cloud.githubusercontent.com/assets/4348935/11109703/3cfe75b8-8958-11e5-8a54-3a0e3640c432.png)

Cheers
Joshi

**Comment by shushiej** [comment]
Did some digging and found the solution here: https://github.com/aterrien/jQuery-Knob#dynamically-configure

Cool WIdget :+1:

**Comment by emilylordahl** [comment]
Hi there @shushiej ,

Looking to solve the same problem and have tried setting the `fgColor` to no avail. Do you mind sharing a more specific solution?

Thanks.
