### ISSUE TITLE
bower install jquery-knob --save leads to a wrong entry in bower.json

### ISSUE THREAD

**Issue by purpleferret** [aterrien/jQuery-Knob#311]
with this command the registered jquery-knob is downloaded but the resulting dependency entry in bower.json does not work:
`"aterrien/jQuery-Knob": "jquery-knob#~1.2.12"`
With this a bower install results in:
`bower jQuery-Knob=jquery-knob#~1.2.12          ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/aterrien/jQuery-Knob=jquery-knob.git", exit code of #128 fatal: remote error:    aterrien/jQuery-Knob=jquery-knob is not a valid repository name   Email support@github.com for help`

I fixed my bower.json with using the following entry instead:
`"jquery-knob": "#~1.2.12"`
(this changes the installation location as well)

**Comment by aterrien** [comment]
Fixed in 1.2.13.
