### ISSUE TITLE
data value is not in middle of knob when using rtl

### ISSUE THREAD

**Issue by jimmyheller** [aterrien/jQuery-Knob#314]
when using rtl direction in page , data value is not in the middle of knob and would be printed in left side with distance and sometimes it would be out of parent element.

**Comment by sorenmp3** [comment]
I solved this by simply adding the following to the input.
style="display:inline;"

It's not stupid if it works :)

**Comment by mortezakarimi** [comment]
@jimmyheller 
I solve this problem with this code in draw function
```js
  $(".knob").knob({
            draw: function () {
               //style rtl
                this.i.css({
                    'margin-right': '-' + ((this.w * 3 / 4 + 2) >> 0) + 'px',
                    'margin-left': 'auto'
                });
            },
        });
```

**Comment by JavaTMP** [comment]
Thank you @mortezakarimi , your solution worked for us too.
