### ISSUE TITLE
Knob is not working

### ISSUE THREAD

**Issue by sakshi-kataria** [aterrien/jQuery-Knob#319]
at page load knob is working but at drop down change knob image not change as per value updated
$(function() {
                  $(".knob").knob({'readOnly':true});
                  });

**Comment by sakshi-kataria** [comment]
it is resolved by adding trigger

**Comment by snithfferx** [comment]
I have the same issue when a pill is toogle a tab
I mean, all my knobs are hide and when the tab is active, they not showing at all.
