### ISSUE TITLE
Http Request  $Ajax --> state.cgi response  

### ISSUE THREAD

**Issue by stephanhartmann81** [aterrien/jQuery-Knob#320]
Hi 
maybe someone can help me with this , hope so ...

I make a request to a server with a state.cgi file ( theres some Datapoints with values in it that i need ) 
with a $Ajax .
that works fine , but the response looks like that :

![unbenannt](https://cloud.githubusercontent.com/assets/12152598/12976419/3abb3454-d0c4-11e5-8274-3f3fb3d0a5ba.JPG)

so now i need the ## value='21.000000 ## from that respons to show it in the knob.

this is the code from the ajax call:

![scriptknob](https://cloud.githubusercontent.com/assets/12152598/12976444/6ad041d4-d0c4-11e5-9603-e5e6758c8003.JPG)

**Comment by stephanhartmann81** [comment]
no one can help me ?

**Comment by HaykoKoryun** [comment]
since it looks like you are using `jQuery`, what you will need to do is use it to parse the result of the `ajax` call as an `xml` document (since that's what the result is) to extract the value, and _then_ set the `knob` value.

**Comment by stephanhartmann81** [comment]
Yeah thats what iam talking about , but i didnt know how i can do that , parse the value ...you know :)

**Comment by HaykoKoryun** [comment]
Here's a working example at [jsfiddle.net](https://jsfiddle.net/HaykoKoryun/zotc4ek8/). The important part of the code is this:

``` javascript
success:function(xml)
{
  var value = $(xml).find("datapoint").attr("value");
}
```

Once you have wrapped the `xml` result with jQuery, you can effectively treat it like a `HTML` document.

**Comment by stephanhartmann81** [comment]
hey man thank you very much for that , you helped me a lot !
