### ISSUE TITLE
Can I use an array of values?

### ISSUE THREAD

**Issue by tracs** [aterrien/jQuery-Knob#346]
Can I use an array of values on my knob? 
Like: 20,30,60,100,200,400,800

**Comment by tracs** [comment]
Solved by:

var values = [20, 30, 60, 100, 200, 400, 800];

$(".foo").knob({
  min: 0,
  max: values.length - 1,
  step: 1,
  format: function(v) {
    return values[v];
  }
});

**Comment by xpectmore** [comment]
if you use my code you will not need  even any array
https://github.com/aterrien/jQuery-Knob/issues/365
