### ISSUE TITLE
Doesn't work properly with JQuery Mobile

### ISSUE THREAD

**Issue by mike20030405** [aterrien/jQuery-Knob#40]
With JQuery Mobile 1.2.0, the data-displayInput box can't be positioned properly, other functions work good;
To verify the issue, just add following two lines into the HTML head section

```
    <link rel="stylesheet" href="http://code.jquery.com/mobile/1.2.0-alpha.1/jquery.mobile-1.2.0-alpha.1.min.css" />
    <script src="http://code.jquery.com/mobile/1.2.0-alpha.1/jquery.mobile-1.2.0-alpha.1.min.js"></script>      
```

Also tried with previous JQuery Mobile 1.1.1, had the same issue;
Also Tried with more early JQuery Mobile 1.0a4.1, the index.html even didn't show up.

**Comment by JakubHromada** [comment]
Thank you enndott!
