### ISSUE TITLE
HttpRequest ?

### ISSUE THREAD

**Issue by thecatz** [aterrien/jQuery-Knob#70]
Hello, can someone can tel me how this gauge can work with httprequest (ajax). Is there any sample code to see how is it work ?

Or can someone tel me how to put my value from my ajax request on the input value=""

Thx

**Comment by pafgoncalves** [comment]
I have a AJAX mechanism that loads a new knob (not just the value but the all html).
`<div class="progress-circular">
   <input type="text" class="knob" value="0" rel="35" data-linecap="round" data-width="200" data-bgcolor="#f2f2f2" data-fgcolor="#c10841" data-thickness=".15" data-readonly="true" disabled="">
< /div>`
How can i make it display and animate?
