### ISSUE TITLE
Responsive support?

### ISSUE THREAD

**Issue by ervasive** [aterrien/jQuery-Knob#98]
Is there any way to use this beautiful plugin in responsive way?

I mean, we can change some of its values (e.g. width, height etc.) on <code>$(window).resize();</code>

``` javascript
$(window).resize(function() {
    knob.trigger('configure', {
        width: 'width-value',
        height: 'height-value'
    });
});
```

And it redraws the <code>canvas</code> element, which is used to render the knob, but it doesn't update the 'width' and 'height' attributes of generated <code>div</code> which contains the <code>canvas</code> and the canvas attributes too.

**Comment by vpxavier** [comment]
Up

**Comment by Jedarc** [comment]
Very good! But unfortunately has a small detail. When resizing the screen, everything works fine. But by clicking the maximize button in the browser, resizing doesn't work.
